package eu.theracraft.theraranks.utilities;

import eu.theracraft.theraranks.TheraRanks;
import java.io.File;
import java.io.IOException;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

public class Configuration {
   private final File dFile;
   private final FileConfiguration data;

   public Configuration(TheraRanks plugin) {
      if (!plugin.getDataFolder().exists()) {
         plugin.getDataFolder().mkdir();
      }

      this.dFile = new File(plugin.getDataFolder(), "data.yml");
      if (!this.dFile.exists()) {
         try {
            this.dFile.createNewFile();
         } catch (IOException var3) {
            Bukkit.getLogger().severe(ChatColor.RED + "Could not create data.yml!");
         }
      }

      this.data = YamlConfiguration.loadConfiguration(this.dFile);
      this.data.set("Warning", "Do not edit this file! It can cause the whole plugin to corrupt!!");
   }

   public FileConfiguration getData() {
      return this.data;
   }

   public void saveData() {
      try {
         this.data.save(this.dFile);
      } catch (IOException var2) {
         Bukkit.getLogger().severe(ChatColor.RED + "Could not save data.yml!");
      }

   }
}
